$PROGRAMS_COLLECTION = @(
    @{ Name         = "Visual Studio Community 2022"
        Source      = "winget"
        Id          = "Microsoft.VisualStudio.2022.Community"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Visual Studio 2022 Build Tools"
        Source      = "winget"
        Id          = "Microsoft.VisualStudio.2022.BuildTools"
        Installer   = "winget"
        Description = "standalone toolset, build and compile applications without having to install the full Visual Studio Integrated Development Environment (IDE)"
    }
    # @{ Name         = "Remote Desktop Client"
    #     Source      = "winget"
    #     Id          = "Microsoft.RemoteDesktopClient"
    #     Installer   = "winget"
    #     Description = ""
    # }
    @{ Name         = "Microsoft Visual C++ 2015-2022 Redistributable (x86)"
        Source      = "winget"
        Id          = "Microsoft.VCRedist.2015+.x64"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Visual C++ 2015-2022 Redistributable (x64)"
        Source      = "winget"
        Id          = "Microsoft.VCRedist.2015+.x86"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name         = "Microsoft Garage Mouse without Borders "
    #     Source      = "winget"
    #     Id          = "Microsoft.MouseWithoutBorders"
    #     Installer   = "winget"
    #     Description = "control multiple (windows only) computers using a single mouse and keyboard,Clipboard Sharing,File Drag-and-Drop and work across different networks with some additional setup"
    # }
    @{ Name         = "Google Chrome"
        Source      = "winget"
        Id          = "Google.Chrome"
        Installer   = "winget"
        Description = "Browser"
    }
    @{ Name         = "Chrome Remote Desktop Host"
        Source      = "winget"
        Id          = "Google.ChromeRemoteDesktopHost"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Google Drive"
        Source      = "winget"
        Id          = "Google.GoogleDrive"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Google Play Games beta"
        Source      = "winget"
        Id          = "Google.PlayGames.Beta"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Android Studio"
        Source      = "winget"
        Id          = "Google.AndroidStudio"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name         = "Ubuntu 24.04 LTS"
    #     Source      = "msstore"
    #     Id          = "9NZ3KLHXDJP5"
    #     Installer   = "winget"
    #     Description = ""
    # }
    # @{ Name         = "WSA System Control"
    #     Source      = "winget"
    #     Id          = "infinitepower18.WSASystemControl"
    #     Installer   = "winget"
    #     Description = ""
    # }
    @{ Name         = "PDFtk Free"
        Source      = "winget"
        Id          = "PDFLabs.PDFtk.Free"
        Installer   = "winget"
        Description = "PDF merge"
    }
    # @{ Name         = "JPEGView"
    #     Source      = "winget"
    #     Id          = "sylikc.JPEGView"
    #     Installer   = "winget"
    #     Description = ""
    # }
    @{ Name         = "EarTrumpet"
        Source      = "winget"
        Id          = "File-New-Project.EarTrumpet"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Node.js"
        Source      = "winget"
        Id          = "OpenJS.NodeJS"
        Installer   = "winget"
        Description = "NodeJS"
    }
    # @{ Name = "MEGAsync"
    #     Source = "winget"
    #     Id = "Mega.MEGASync"
    #     Installer = "winget"
    #     Description = ""
    # }
    @{ Name         = "FFmpeg"
        Source      = "winget"
        Id          = "Gyan.FFmpeg"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name = "Calibre"
    #     Source = "winget"
    #     Id = "calibre.calibre"
    #     Installer = "winget"
    #     Description = "Open book files like epub"
    # }
    @{ Name         = "Brave"
        Source      = "winget"
        Id          = "Brave.Brave"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name = "HandBrake"
    #     Source = "winget"
    #     Id = "HandBrake.HandBrake"
    #     Installer = "winget"
    #     Description = "Video conversion"
    # }
    @{ Name         = "GitHub CLI"
        Source      = "winget"
        Id          = "GitHub.cli"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name = "Kdenlive"
    #     Source = "winget"
    #     Id = "KDE.Kdenlive"
    #     Installer = "winget"
    #     Description = "Video editor, production"
    # }
    @{ Name         = "Firefox"
        Source      = "winget"
        Id          = "Mozilla.Firefox"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name = "ONLYOFFICE Desktop Editors"
    #     Source = "winget"
    #     Id = "ONLYOFFICE.DesktopEditors"
    #     Installer = "winget"
    #     Description = "PDF Editor"
    # }
    @{ Name         = "LibreOffice"
        Source      = "winget"
        Id          = "TheDocumentFoundation.LibreOffice"
        Installer   = "winget"
        Description = "For Documents"
    }
    # @{ Name = "NAPS2"
    #     Source = "winget"
    #     Id = "Cyanfish.NAPS2"
    #     Installer = "winget"
    #     Description = "OCR and merge for pdf"
    # }
    @{ Name         = "OBS Studio"
        Source      = "winget"
        Id          = "OBSProject.OBSStudio"
        Installer   = "winget"
        Description = "Video stream and record"
    }
    # @{ Name = "VirtualBox"
    #     Source = "winget"
    #     Id = "Oracle.VirtualBox"
    #     Installer = "winget"
    #     Description = "Don't forget to install VB Extensions"
    # }
    @{ Name         = "Process Monitor (procmon)"
        Source      = "winget"
        Id          = "Microsoft.Sysinternals.ProcessMonitor"
        Installer   = "winget"
        Description = "Log real-time file system, registry, and process/thread activity"
    }
    # @{ Name = "Postman"
    #     Source = "winget"
    #     Id = "Postman.Postman"
    #     Installer = "winget"
    #     Description = "For backend request tests"
    # }
    @{ Name         = "Python 3.13"
        Source      = "winget"
        Id          = "Python.Python.3.13"
        Installer   = "winget"
        Description = "Python 3.13 (change the version in the future)"
    }
    # @{ Name = "Telegram Desktop"
    #     Source = "winget"
    #     Id = "Telegram.TelegramDesktop"
    #     Installer = "winget"
    #     Description = ""
    # }
    @{ Name         = "TeraCopy"
        Source      = "winget"
        Id          = "CodeSector.TeraCopy"
        Installer   = "winget"
        Description = "File copy, paste"
    }
    # @{ Name = "qBittorrent"
    #     Source = "winget"
    #     Id = "qBittorrent.qBittorrent"
    #     Installer = "winget"
    #     Description = ""
    # }
    @{ Name         = "Revo Uninstaller"
        Source      = "winget"
        Id          = "RevoUninstaller.RevoUninstaller"
        Installer   = "winget"
        Description = "Fully uninstall Windows programs(with leftover)"
    }
    # @{ Name = "VLC"
    #     Source = "winget"
    #     Id = "VideoLAN.VLC"
    #     Installer = "winget"
    #     Description = ""
    # }
    @{ Name         = "Tor Browser"
        Source      = "winget"
        Id          = "TorProject.TorBrowser"
        Installer   = "winget"
        Location    = "C:\TorBrowser"
        Description = "This is a portable version of Tor"
    }
    # @{ Name = "NVIDIA GeForce NOW"
    #     Source = "winget"
    #     Id = "Nvidia.GeForceNow"
    #     Installer = "winget"
    #     Description = ""
    # }
    @{ Name         = "AnyBurn"
        Source      = "winget"
        Id          = "PowerSoftware.AnyBurn"
        Installer   = "winget"
        Description = "CD / DVD / Blu-ray burning, Append data to disc, Create or edit image files"
    }
    # @{ Name = "Zoom"
    #     Source = "winget"
    #     Id = "Zoom.Zoom"
    #     Installer = "winget"
    #     Description = ""
    # }
    # @{ Name         = "ZoomRemoteControl"
    #     Source      = "winget"
    #     Id          = "Zoom.ZoomRemoteControl"
    #     Installer   = "winget"
    #     Description = "Remotely control another participant's computer"
    # }
    @{ Name         = "ZoomIt"
        Source      = "winget"
        Id          = "Microsoft.Sysinternals.ZoomIt"
        Installer   = "winget"
        Description = "screen zoom, annotation, and recording tool for technical presentations and demos"
    }
    # @{ Name         = "Looking Glass"
    #     Source      = "winget"
    #     Id          = "gnif.LookingGlass"
    #     Installer   = "winget"
    #     Description = ""
    # }
    @{ Name         = "Avidemux"
        Source      = "winget"
        Id          = "Avidemux.Avidemux"
        Installer   = "winget"
        Description = "Fast video split, cut, etc."
    }
    @{ Name         = "7-Zip"
        Source      = "winget"
        Id          = "7zip.7zip"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft 365 Apps for enterprise"
        Source      = "winget"
        Id          = "Microsoft.Office"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Sticky Notes"
        Source      = "msstore"
        Id          = "9NBLGGH4QGHW"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Whiteboard"
        Source      = "msstore"
        Id          = "9MSPC6MP8FM4"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Notepad"
        Source      = "msstore"
        Id          = "9MSMLRH6LZF3"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Scan"
        Source      = "msstore"
        Id          = "9WZDNCRFJ3PV"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Sound Recorder"
        Source      = "msstore"
        Id          = "9WZDNCRFHWKN"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Photos"
        Source      = "msstore"
        Id          = "9WZDNCRFJBH4"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Calculator"
        Source      = "msstore"
        Id          = "9WZDNCRFHVN5"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Snipping Tool"
        Source      = "msstore"
        Id          = "9MZ95KL8MR0L"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Paint"
        Source      = "msstore"
        Id          = "9PCFS5B6T72H"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Clock"
        Source      = "msstore"
        Id          = "9WZDNCRFJ3PR"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Net Speed Meter"
        Source      = "msstore"
        Id          = "9NMBX01PXZ4L"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Edge"
        Source      = "winget"
        Id          = "Microsoft.Edge"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Edge WebView2 Runtime"
        Source      = "winget"
        Id          = "Microsoft.EdgeWebView2Runtime"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Windows Camera"
        Source      = "msstore"
        Id          = "9WZDNCRFJBBG"
        Installer   = "winget"
        Description = ""
    }
    # @{ Name         = "Outlook for Windows"
    #     Source      = "msstore"
    #     Id          = "9NRX63209R7B"
    #     Installer   = "winget"
    #     Description = ""
    # }
    @{ Name         = "Microsoft OneDrive"
        Source      = "winget"
        Id          = "Microsoft.OneDrive"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Microsoft Teams"
        Source      = "winget"
        Id          = "Microsoft.Teams"
        Installer   = "winget"
        Description = ""
    }
    @{ Name         = "Snappy Driver Installer"
        Source      = "winget"
        Id          = "samlab-ws.SnappyDriverInstaller"
        Installer   = "winget"
        Description = ""
    }
)
# @{ Name         = ""
#     Source      = ""
#     Id          = ""
#     Installer   = "winget"
#     Description = ""
# }
# Windows Configuration Designer                   9NBLGGH4TX22             Unknown  msstore
# Vim                                   vim.vim                                      9.1.0618             Tag: te… winget